name: flourish
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  image: ^4.5.3
  image_picker: ^1.1.2
  get_it: ^8.0.3
  icons_plus: ^5.0.0
  camerawesome: ^2.4.0
  objectbox: 4.1.0
  objectbox_flutter_libs: 4.1.0
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  objectbox_generator: 4.1.0

flutter_icons:
  image_path: 'assets/images/logo.png'
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/